// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghsdbpqgoxwufhkrqcfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdoc2RicHFnb3h3dWZoa3JxY2ZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ0NTE0OTgsImV4cCI6MjA1MDAyNzQ5OH0.j0UNfRjXOtssp41H1MWl2WkNVa1JCo3OKuUmdsAhBDY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);